
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wrover]
platform = espressif32
board = upesy_wrover
framework = arduino
monitor_speed = 115200
; If your camera board is AI-Thinker (ESP32-CAM module) enable the define below by uncommenting:
; build_flags = -D CAMERA_MODEL_AI_THINKER
; Adjust build_flags to match your camera wiring/model if needed
